### ISSUE TITLE
Doesn't work out of box

### ISSUE THREAD

**Issue by MagnusBrzenk** [vajahath/open-swagger-ui#5]
Observed behavior on MacOS, node version 14.13.0.:

```
npm i -g open-swagger-ui
open-swagger-ui https://raw.githubusercontent.com/vajahath/open-swagger-ui/master/tests/swagger.json
# ---->
# ✔ Loading file https://raw.githubusercontent.com/vajahath/open-swagger-ui/master/tests/swagger.json
# Swagger open on port 49887
# Open localhost:49887 in browser and get "404 not found" error
```

**Comment by vajahath** [comment]
OK. This was a documentation issue. The route you need to open is `http://localhost:<port>/swagger-doc/` and not `http://localhost:<port>`.
OR, alternatively, you can use the `---open` flag, so that the cli automatically opens the correct link.
Thanks for reporting.

Let me add a redirection to the correct link.

**Comment by vajahath** [comment]
@MagnusBrzenk Or, let me know if you'd like to PR this. It's very easy as adding a single line.
```ts
app.use((req, res)=>res.redirect('/swagger-doc'))
```
